"use strict";
const KEY="grade9-newton2-v1";
const tasks=[
{id:"basic",type:"одна сила",title:"Тележка массой 2 кг",text:"На тележку действует сила 10 Н вправо. Найди ускорение в м/с².",hint:"a = F/m.",answer:5,solution:"a = 10/2 = 5 м/с² вправо."},
{id:"net",type:"две силы",title:"Сначала равнодействующая",text:"Силы 14 Н вправо и 5 Н влево действуют на тело массой 3 кг. Найди ускорение в м/с², вправо считаем плюсом.",hint:"Fрез = 14 − 5, затем раздели на 3.",answer:3,solution:"Fрез = 9 Н; a = 9/3 = 3 м/с² вправо."},
{id:"grams",type:"единицы СИ",title:"Масса дана в граммах",text:"Сила 6 Н действует на тело массой 500 г. Найди ускорение в м/с².",hint:"500 г = 0,5 кг.",answer:12,solution:"m = 0,5 кг; a = 6/0,5 = 12 м/с²."},
{id:"force",type:"обратная задача",title:"Найди силу",text:"Тело массой 4 кг получает ускорение 2,5 м/с². Найди равнодействующую в ньютонах.",hint:"Из a = F/m следует F = ma.",answer:10,solution:"Fрез = ma = 4 · 2,5 = 10 Н."},
{id:"mass",type:"обратная задача",title:"Найди массу",text:"Равнодействующая 18 Н сообщает телу ускорение 6 м/с². Найди массу в кг.",hint:"m = F/a.",answer:3,solution:"m = 18/6 = 3 кг."},
{id:"direction",type:"знак",title:"Ускорение влево",text:"На тело массой 2 кг действуют 3 Н вправо и 11 Н влево. Введи ускорение со знаком, вправо — плюс.",hint:"Fрез = 3 − 11.",answer:-4,solution:"Fрез = −8 Н; a = −8/2 = −4 м/с², то есть влево."}
];
const solved=load();const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch{return {}}}function save(){localStorage.setItem(KEY,JSON.stringify(solved))}function num(v){const m=String(v).replace(",",".").match(/-?\d+(?:\.\d+)?/);return m?+m[0]:NaN}function near(a,b){return Number.isFinite(a)&&Math.abs(a-b)<.03}
function initTheme(){if(localStorage.getItem("grade9-newton-theme")==="dark")document.documentElement.dataset.theme="dark";$("#themeToggle").onclick=()=>{const n=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=n;localStorage.setItem("grade9-newton-theme",n)}}function initNav(){$$(".nav-btn").forEach(b=>b.onclick=()=>{$$(".nav-btn").forEach(x=>x.classList.toggle("active",x===b));$$(".content-section").forEach(x=>x.classList.toggle("active",x.id===b.dataset.target))})}
function updateLab(message="Меняй по одному параметру и объясняй результат словами."){const m=+$("#mass").value,r=+$("#rightForce").value,l=+$("#leftForce").value,n=r-l,a=n/m,dir=n===0?"":n>0?" →":" ←";$("#massLabel").textContent=m;$("#rightLabel").textContent=r;$("#leftLabel").textContent=l;$("#block").textContent=`${m} кг`;$("#rightForceView").textContent=`${r} Н →`;$("#leftForceView").textContent=`← ${l} Н`;$("#netMeter").textContent=`${Math.abs(n)} Н${dir}`;$("#massMeter").textContent=`${m} кг`;$("#accelMeter").textContent=`${Math.abs(a).toLocaleString("ru-RU",{maximumFractionDigits:2})} м/с²${dir}`;$("#labAnswer").textContent=`a = ${(a).toLocaleString("ru-RU",{maximumFractionDigits:2})} м/с²`;$("#labFeedback").textContent=message}
function calculate(){const r=+$("#calcRight").value,l=+$("#calcLeft").value,raw=+$("#calcMass").value,kg=$("#massUnit").value==="g"?raw/1000:raw,out=$("#calculation");if(!Number.isFinite(r)||!Number.isFinite(l)||!(kg>0)){out.innerHTML="<p>Проверь данные: масса должна быть положительной.</p>";return}const f=r-l,a=f/kg,dir=a===0?"ускорения нет":a>0?"вправо":"влево";out.innerHTML=`<h3>Ответ: a = ${a.toLocaleString("ru-RU",{maximumFractionDigits:3})} м/с² (${dir})</h3><ol><li>Ось направим вправо.</li><li>Масса в СИ: m = ${kg.toLocaleString("ru-RU")} кг.</li><li>Fрез = ${r} − ${l} = ${f} Н.</li><li>a = Fрез/m = ${f}/${kg.toLocaleString("ru-RU")} = ${a.toLocaleString("ru-RU",{maximumFractionDigits:3})} м/с².</li></ol>`}
function renderTasks(){const grid=$("#taskGrid");grid.innerHTML="";tasks.forEach((t,i)=>{const card=document.createElement("article");card.className=`task-card${solved[t.id]?" completed":""}`;card.innerHTML=`<div class="task-meta"><strong>Задача ${i+1}</strong><span>${t.type}</span></div><h3>${t.title}</h3><p>${t.text}</p><div class="answer-row"><input class="task-answer" value="${solved[t.id]?.answer||""}" placeholder="Число"><button class="btn primary check">Проверить</button></div><button class="hint-btn">Показать подсказку</button><div class="hint" hidden>${t.hint}</div><div class="task-feedback${solved[t.id]?" success":""}">${solved[t.id]?`Верно. ${t.solution}`:"Ответ ещё не проверен."}</div>`;$(".hint-btn",card).onclick=e=>{const h=$(".hint",card);h.hidden=!h.hidden;e.currentTarget.textContent=h.hidden?"Показать подсказку":"Скрыть подсказку"};const verify=()=>{const input=$(".task-answer",card),fb=$(".task-feedback",card);if(near(num(input.value),t.answer)){solved[t.id]={answer:input.value};card.classList.add("completed");fb.className="task-feedback success";fb.textContent=`Верно. ${t.solution}`}else{delete solved[t.id];card.classList.remove("completed");fb.className="task-feedback error";fb.textContent="Пока неверно. Проверь равнодействующую, килограммы и деление на массу."}save();score()};$(".check",card).onclick=verify;$(".task-answer",card).onkeydown=e=>{if(e.key==="Enter")verify()};grid.append(card)});score()}function score(){$("#score").textContent=`${tasks.filter(t=>solved[t.id]).length}/${tasks.length}`}
document.addEventListener("DOMContentLoaded",()=>{initTheme();initNav();["#mass","#rightForce","#leftForce"].forEach(s=>$(s).oninput=()=>updateLab());$("#doubleMass").onclick=()=>{const x=$("#mass");x.value=Math.min(10,+x.value*2);updateLab("Масса выросла: при прежней Fрез ускорение уменьшилось.")};$("#doubleForce").onclick=()=>{const r=$("#rightForce"),l=$("#leftForce");r.value=Math.min(20,+r.value*2);l.value=Math.min(20,+l.value*2);updateLab("Обе силы удвоены: проверь, во сколько раз изменилась Fрез.")};$("#calculate").onclick=calculate;$("#resetProgress").onclick=()=>{Object.keys(solved).forEach(k=>delete solved[k]);save();renderTasks()};updateLab();renderTasks()});
