"use strict";
const KEY="grade9-newton1-v1";
const tasks=[
{id:"book",type:"равновесие",title:"Книга на столе",text:"На книгу действует сила тяжести 5 Н вниз и реакция опоры 5 Н вверх. Чему равна равнодействующая?",hint:"Силы противоположны: вычти меньшую из большей.",answer:"0",solution:"Fрез = 5 − 5 = 0 Н, поэтому ускорения нет."},
{id:"car",type:"смысл закона",title:"Автомобиль едет ровно",text:"Автомобиль движется прямо с постоянной скоростью. Обязательно ли на него не действуют силы? Ответь «да» или «нет».",hint:"Двигатель тянет вперёд, сопротивление мешает движению.",answer:"нет",solution:"Нет. Силы могут действовать, но их равнодействующая равна нулю."},
{id:"motion",type:"прогноз",title:"Шайба без сопротивления",text:"Шайба уже движется вправо. Равнодействующая стала равна нулю. Что произойдёт со скоростью?",hint:"Нулевой результат сил означает нулевое ускорение.",answer:"постоян",solution:"Скорость останется постоянной по модулю и направлению."},
{id:"net",type:"векторы",title:"Две горизонтальные силы",text:"На тело действуют 9 Н вправо и 4 Н влево. Введи равнодействующую со знаком: вправо считаем плюсом.",hint:"Fрез = Fвправо − Fвлево.",answer:"5",solution:"Fрез = 9 − 4 = +5 Н, направлена вправо."},
{id:"rest",type:"ловушка",title:"Тело покоится",text:"Если тело сейчас покоится, можно ли только по этому факту утверждать, что Fрез = 0?",hint:"Сразу после начала действия нескомпенсированной силы скорость ещё может быть нулевой.",answer:"нет",solution:"Нет. Нужны сведения об ускорении или о силах, а не только мгновенная скорость."},
{id:"frame",type:"условие",title:"Где выполняется закон",text:"В какой системе отсчёта формулируют первый закон Ньютона?",hint:"Название начинается со слова «инерциальная».",answer:"инерциал",solution:"В инерциальной системе отсчёта."}
];
const solved=load();
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function norm(v){return String(v??"").trim().toLowerCase().replaceAll("ё","е").replaceAll("−","-")}
function load(){try{return JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch{return {}}}
function save(){localStorage.setItem(KEY,JSON.stringify(solved))}
function initTheme(){if(localStorage.getItem("grade9-newton-theme")==="dark")document.documentElement.dataset.theme="dark";$("#themeToggle").onclick=()=>{const n=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=n;localStorage.setItem("grade9-newton-theme",n)}}
function initNav(){$$(".nav-btn").forEach(b=>b.onclick=()=>{$$(".nav-btn").forEach(x=>x.classList.toggle("active",x===b));$$(".content-section").forEach(x=>x.classList.toggle("active",x.id===b.dataset.target))})}
function updateLab(){const r=+$("#rightForce").value,l=+$("#leftForce").value,net=r-l;$("#rightLabel").textContent=r;$("#leftLabel").textContent=l;$("#rightArrow span").textContent=`${r} Н`;$("#leftArrow span").textContent=`${l} Н`;$("#rightArrow").style.opacity=r?1:.2;$("#leftArrow").style.opacity=l?1:.2;$("#netMeter").textContent=`${net>0?"+":""}${net} Н`;$("#accelMeter").textContent=net===0?"0":"не равно 0";$("#motionMeter").textContent=net===0?"v постоянна":net>0?"v изменяется вправо":"v изменяется влево";$("#lawBadge").textContent=`Fрез = ${net} Н`;return net}
function run(){const net=updateLab(),choice=$("input[name=prediction]:checked")?.value,correct=net===0?"constant":net>0?"right":"left",v=+$("#velocity").value||0,box=$("#labFeedback");if(!choice){box.className="feedback error";box.textContent="Сначала выбери прогноз.";return}$("#cart").style.transform=`translateX(${Math.max(-180,Math.min(180,v*10+net*12))}px)`;box.className=`feedback ${choice===correct?"success":"error"}`;box.textContent=choice===correct?(net===0?`Верно: Fрез = 0, поэтому скорость ${v} м/с сохраняется.`:`Верно: Fрез = ${Math.abs(net)} Н ${net>0?"вправо":"влево"}, поэтому скорость изменяется.`):"Прогноз не совпал. Сначала найди Fрез с учётом направлений."}
function check(task,value){const n=norm(value);if(task.id==="net")return Number(n)===5;return n.includes(task.answer)}
function renderTasks(){const grid=$("#taskGrid");grid.innerHTML="";tasks.forEach((t,i)=>{const card=document.createElement("article");card.className=`task-card${solved[t.id]?" completed":""}`;card.innerHTML=`<div class="task-meta"><strong>Задача ${i+1}</strong><span>${t.type}</span></div><h3>${t.title}</h3><p>${t.text}</p><div class="answer-row"><input class="task-answer" value="${solved[t.id]?.answer||""}" placeholder="Ваш ответ"><button class="btn primary check">Проверить</button></div><button class="hint-btn">Показать подсказку</button><div class="hint" hidden>${t.hint}</div><div class="task-feedback${solved[t.id]?" success":""}">${solved[t.id]?`Верно. ${t.solution}`:"Ответ ещё не проверен."}</div>`;$(".hint-btn",card).onclick=e=>{const h=$(".hint",card);h.hidden=!h.hidden;e.currentTarget.textContent=h.hidden?"Показать подсказку":"Скрыть подсказку"};const verify=()=>{const input=$(".task-answer",card),fb=$(".task-feedback",card);if(check(t,input.value)){solved[t.id]={answer:input.value};card.classList.add("completed");fb.className="task-feedback success";fb.textContent=`Верно. ${t.solution}`}else{delete solved[t.id];card.classList.remove("completed");fb.className="task-feedback error";fb.textContent="Пока неверно. Проверь направление сил и смысл закона."}save();score()};$(".check",card).onclick=verify;$(".task-answer",card).onkeydown=e=>{if(e.key==="Enter")verify()};grid.append(card)});score()}
function score(){$("#score").textContent=`${tasks.filter(t=>solved[t.id]).length}/${tasks.length}`}
document.addEventListener("DOMContentLoaded",()=>{initTheme();initNav();["#rightForce","#leftForce"].forEach(s=>$(s).oninput=updateLab);$("#runBtn").onclick=run;$("#balanceBtn").onclick=()=>{$("#leftForce").value=$("#rightForce").value;updateLab();$("#labFeedback").textContent="Силы уравнены. Теперь Fрез = 0."};$("#resetProgress").onclick=()=>{Object.keys(solved).forEach(k=>delete solved[k]);save();renderTasks()};updateLab();renderTasks()});
